"""add ai job tables

Revision ID: cf694d9651c7
Revises: 21125e94e2f3
Create Date: 2026-07-31 13:39:29.582399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf694d9651c7'
down_revision: Union[str, None] = '21125e94e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('model_identifier', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validated_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_field_predictions',
    sa.Column('ai_job_id', sa.UUID(), nullable=False),
    sa.Column('field_code', sa.String(length=64), nullable=False),
    sa.Column('proposed_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_snippet', sa.String(length=512), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ai_job_id'], ['ai_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_feedback',
    sa.Column('ai_field_prediction_id', sa.UUID(), nullable=False),
    sa.Column('proposed_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('correction_reason', sa.String(length=512), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('corrected_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ai_field_prediction_id'], ['ai_field_predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_feedback')
    op.drop_table('ai_field_predictions')
    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
